### ISSUE TITLE
Building lib for Android: cannot find -lrt

### ISSUE THREAD

**Issue by liujunhg** [01org/vmf#10]
I use NDK r10b standalone toolschain Building lib for Android ;

run compile_for_android.bat
error info:

> [ 91%] Building CXX object modules/CMakeFiles/vmf.dir/vmfcore/src/details/object_factory.cpp.o
> [ 91%] Linking CXX shared library ..\lib\libvmf.so
> D:/android-ndk-r10b/toolchains/x86-4.8/prebuilt/windows-x86_64/bin/../lib/gcc/i686-linux-android/4.8/../../../../i686-linux-android/bin/ld.exe: error: cannot find -lrt
> collect2.exe: error: ld returned 1 exit status
> make[2]: **\* [lib/libvmf.so] Error 1
> make[1]: **\* [modules/CMakeFiles/vmf.dir/all] Error 2
> make: **\* [all] Error 2

I don't know much about librt, but as far as I understand, the NDK does not include librt, but instead integrates some of it's functionality in Android's libc.

How fix this error?
please help me! thanks

**Comment by eaniemey** [comment]
I have a patch for this I just merged -> https://github.com/01org/vmf/commit/0d4e4ce3db73fce7dedb26c3558e9df245b69af2. 

Please pull and test it. Thanks for bringing it to our attention.
