### ISSUE TITLE
Could I inject 360 metadata into video with this framework?

### ISSUE THREAD

**Issue by tomtomtong** [01org/vmf#12]
Hello. Could I use your framework in iOS to inject 360 metadata into video such like the Google code below done?
https://github.com/google/spatial-media

**Comment by eaniemey** [comment]
Short answer is yes. We support metadata injection for a variety of video container that support 360 video such as MP4 and Matroska.

Long answer really depends on how you are capturing the metadata and what metadata you wish to store. Can you elaborate a little on your intended usage?

Erik

**Comment by tomtomtong** [comment]
Facebook and Youtube needs the video associated with 360 metadata if you want to drag and browse the 360 video  such like the link below.
https://www.youtube.com/watch?v=-xNN-bJQ4vI

The statement below is reference to this link. It is about metadata specification.
https://github.com/google/spatial-media/blob/master/docs/spherical-video-rfc.md

Spherical video metadata is stored in a uniquely-identified moov.trak.uuid box to avoid collisions with other potential metadata. This box shall cite the UUID value ffcc8263-f855-4a93-8814-587a02521fdd. The XML metadata itself is written within the uuid leaf as a UTF-8 string.

**Comment by eaniemey** [comment]
Hi Tom,

I looked through your intended use and VMF should work for this scenario. VMF can insert metadata specifically referenced to a given frame or timestamp in a video file.

If Javascript is your preferred language, you should take a look at our about to be released version 3.0 code. It is located here -> https://github.com/apavlenko/vmf. This new version has significant enhancements to the Java/Javascript bindings.

Also, the new version has a new group of sample apps including an iOS app.

Let me know if this answers your questions,

Erik

**Comment by tomtomtong** [comment]
Thank. I have tried the iOS sample and downloaded VMF iOS framework from Intel page.
But #import <vmf/vmf.hpp> has the error "vmf/vmf.hpp is not found"

**Comment by eaniemey** [comment]
Did you clone v2.0.2 or 3.0?

Also, did you go through the complete cmake config process?

Erik

**Comment by tomtomtong** [comment]
I only try to download the framework from this link.
 https://software.intel.com/en-us/vmf-sdk

**Comment by eaniemey** [comment]
That is VMF 2.0.2.

You need to download the source and build v3.0 to get the new Java/Javascript bindings and the new iOS sample application.

Please use the link I provided before -> https://github.com/apavlenko/vmf

Binary packages will be available in the next couple of weeks when the documentation is complete.

Erik

**Comment by tomtomtong** [comment]
Thx. I succeed to build the iOS framework by cMake command. I would like to inject 360 metadata with the approach below. 

First, I use Google Metadata Tool to insert metadata to a video.
Second, I use that video as a template and make reference to its metadata schema with the SDK
Third, I insert the metadata to a new video by that reference with the SDK

Is this approach feasible and much simple than creating a new 360 schema?

Thank you for your patience again as I have many questions.

**Comment by eaniemey** [comment]
The Google metadata tool metadata is not compatible with VMF. You will need to convert the metadata into a VMF compatible form.

Question: Why not just use VMF throughout your solution to insert the metadata?

Erik

**Comment by tomtomtong** [comment]
I am afraid there is any incompatible issues during conversion between different format. And I am not quite familiar with VMF SDK methods. So I want to refer it directly.
