### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [01org/vmf#2]
I would like to point out that identifiers like "[`__VMF_DATASOURCE_HPP__`](https://github.com/01org/vmf/blob/790d307ef38dee488911b2e14cea0d84dfc29259/modules/vmdatasource/include/vmf/vmdatasource.hpp#L15)" and "[`__VMF_IQUERY_H__`](https://github.com/01org/vmf/blob/790d307ef38dee488911b2e14cea0d84dfc29259/modules/vmfcore/include/vmf/iquery.hpp#L24)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by eaniemey** [comment]
That is a great catch Markus. Thanks for bringing it up. We definitely want to correct issues like this in VMF. 

If you would like to contribute further by submitting a patch to correct the naming convention issues we would be happy to work with you to merge it. 

 Erik

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?

**Comment by eaniemey** [comment]
Again thanks for bringing this issue to our attention. Can you provide a specific example of this problem in VMF code and even a suggested fix?

**Comment by elfring** [comment]
Would you like to [delete any underscores from mentioned identifiers](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797)?

How do you think about to keep this issue open until the affected implementation details will really be fixed?
